# Generated by Django 3.2 on 2022-12-02 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='face/images/')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('age_group', models.CharField(choices=[('youth', 'Youth'), ('middle', 'Middle-Aged'), ('senior', 'Senior')], default=0, max_length=12)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='메뉴명')),
                ('price', models.IntegerField(default='0', verbose_name='가격')),
                ('image', models.ImageField(upload_to='menu/images/')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('calorie', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(blank=True, upload_to='model/')),
                ('type', models.CharField(choices=[('CNN', 'cnn'), ('DNN', 'dnn'), ('RandomForest', 'rf'), ('KNN', 'knn'), ('SGD', 'sgd'), ('XGB', 'xgb')], default='CNN', max_length=12)),
                ('version', models.CharField(max_length=10)),
                ('comment', models.CharField(default=' ', max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cafe.customer')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.menu')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='version',
            field=models.ForeignKey(db_column='version', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='versionR', to='cafe.model'),
        ),
    ]
