# Generated by Django 3.2 on 2022-12-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('hot_coffee', 'Hot Coffee'), ('ice_coffee', 'Ice Coffee'), ('non_coffee', 'Non Coffee'), ('smoothie', 'Smoothie'), ('bread', 'Bread')], default=0, max_length=20),
        ),
    ]
