# Generated by Django 3.2 on 2022-12-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_best_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=0, verbose_name='수량'),
        ),
    ]
