# Generated by Django 3.2 on 2022-12-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20221205_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='type',
        ),
    ]
