# Generated by Django 3.2 on 2022-12-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='desc',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
