# Generated by Django 3.2 on 2022-12-14 02:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_auto_20221214_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 500], upload_to='menu/images/'),
        ),
    ]
